name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
           nix build -f ./default.nix streamImage -L

      - name: Tag and push image
        id: docker_push
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_TAG_LATEST=ghcr.io/${GITHUB_REPOSITORY@L}:latest-arm64
          IMAGE_TAG=ghcr.io/${GITHUB_REPOSITORY@L}:$TIMESTAMP-arm64
          ./result | docker load
          docker tag next-test:latest $IMAGE_TAG_LATEST
          docker tag next-test:latest $IMAGE_TAG
          docker push $IMAGE_TAG_LATEST
          docker push $IMAGE_TAG
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Install Nomad
        uses: hashicorp/setup-nomad@main

      - name: Request deployment to Nomad
        env:
          NOMAD_ADDR: https://nomad.ayats.org
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          NOMAD_HTTP_AUTH: ${{ secrets.NOMAD_HTTP_AUTH }}
        run: |
          nomad run -var="tag=${{ steps.docker_push.outputs.image_tag }}" ./app.nomad
