name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        image: [ubuntu-24.04-arm, ubuntu-24.04]
    runs-on: ${{ matrix.image }}
    permissions:
      packages: write
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
           nix build -f ./default.nix streamImage -L

      - name: Tag and push image
        id: docker_push
        run: |
          ARCH="$(docker info --format json | jq -r '.ClientInfo.Arch')"
          IMAGE_TAG=ghcr.io/${GITHUB_REPOSITORY@L}:${{ github.sha }}-$ARCH
          ./result | docker load
          docker tag next-test:latest $IMAGE_TAG
          docker push $IMAGE_TAG
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  # merge:
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     packages: write
  #   steps:
  #     - run: |
  #         docker pull ghcr.io/${GITHUB_REPOSITORY@L}

  # deploy:
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     packages: write
  #   steps:
  #     - name: Install Nomad
  #       uses: hashicorp/setup-nomad@main

  #     - name: Request deployment to Nomad
  #       env:
  #         NOMAD_ADDR: https://nomad.ayats.org
  #         NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
  #         NOMAD_HTTP_AUTH: ${{ secrets.NOMAD_HTTP_AUTH }}
  #       run: |
  #         nomad run -var="tag=${{ steps.docker_push.outputs.image_tag }}" ./app.nomad
